JESI-2336
jesims/clojure-polyline pull request #1
Opened 2018-11-01 03:29 UTC by axrs

[JESI-2336](https://jesims.atlassian.net/browse/JESI-2336)

2018-11-06 22:59 UTC, AndreTheHunter requested changes
WIP Review

2018-11-06 22:59 UTC, AndreTheHunter commented on src/com/michaelgaare/clojure_polyline.cljc
> +  #?(:clj  (.append sb c)
Add type hints for the CLJ code so reflection isn't used

2018-11-06 23:40 UTC, ElizabethForest submitted a review, later dismissed

2018-11-07 00:01 UTC, AndreTheHunter approved these changes

2018-11-07 00:02 UTC, AndreTheHunter requested changes

2018-11-07 00:02 UTC, AndreTheHunter commented on project.clj
> +(defproject com.michaelgaare/clojure-polyline "0.4.1-SNAPSHOT"
Change project to jesi and setup CI and deploys

2018-11-07 00:53 UTC, AndreTheHunter approved these changes

2018-11-07 00:57 UTC, ElizabethForest approved these changes

2018-11-07 00:58 UTC, merged